export const NOTIFICATIONS_MOCK = [
  {
    id: '1',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 5',
    time: '2024-03-15 17:00:00',
    isRead: false,
  },
  {
    id: '2',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 6',
    time: '2022-01-02 17:00:00',
    isRead: false,
  },
  {
    id: '3',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 7',
    time: '2024-03-31 17:00:00',
    isRead: false,
  },
  {
    id: '4',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 8',
    time: '2024-01-02 17:00:00',
    isRead: false,
  },
  {
    id: '5',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 9',
    time: '2024-01-02 17:00:00',
    isRead: false,
  },
  {
    id: '6',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project X',
    time: '2024-01-02 17:00:00',
    isRead: false,
  },
  {
    id: '7',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 11',
    time: '2024-01-02 17:00:00',
    isRead: false,
  },
  {
    id: '8',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 12',
    time: '2024-01-02 17:00:00',
    isRead: true,
  },
  {
    id: '9',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 13',
    time: '2024-01-02 17:00:00',
    isRead: true,
  },
  {
    id: '10',
    image: '/images/person02.webp',
    approver: 'David Paman',
    task: 'Bill of Quantities - Project 14',
    time: '2024-01-02 17:00:00',
    isRead: true,
  },
];
