export const TASK_WIDGET_DATA = [
  {
    id: 1,
    title: 'Create bill of Quantity for Project 3',
    time: '2024-01-02 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 2,
    title: 'Create bill of Quantity for Project 4',
    time: '2024-02-03 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 3,
    title: 'Create bill of Quantity for Project 6',
    time: '2024-03-04 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 4,
    title: 'Create bill of Quantity for Project 7',
    time: '2024-03-12 17:00:00',
    isDone: true,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 5,
    title: 'Create bill of Quantity for Project 8',
    time: '2024-03-12 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 6,
    title: 'Create bill of Quantity for Project 9',
    time: '2024-03-16 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 7,
    title: 'Create bill of Quantity for Project 11',
    time: '2024-02-28 17:00:00',
    isDone: false,
    isPastDue: true,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 8,
    title: 'Create bill of Quantity for Project 12',
    time: '2024-01-18 17:00:00',
    isDone: true,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 9,
    title: 'Create bill of Quantity for Project 13',
    time: '2024-03-31 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
  {
    id: 10,
    title: 'Create bill of Quantity for Project 14',
    time: '2024-01-02 17:00:00',
    isDone: false,
    isPastDue: true,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
  },
];
