export const TASK_WIDGET_DATA = [
  {
    id: 1,
    title: 'Create bill of Quantity for Project 3',
    time: '2024-01-02 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Jane Smith' },
    boardLane: { name: 'Backlog' },
    timeAgo: '1 month ago',
  },
  {
    id: 2,
    title: 'Create bill of Quantity for Project 4',
    time: '2024-02-03 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'John Doe' },
    boardLane: { name: 'In progress' },
    timeAgo: '2 days ago',
  },
  {
    id: 3,
    title: 'Create bill of Quantity for Project 6',
    time: '2024-03-04 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Vince Carter' },
    boardLane: { name: 'Backlog' },
    timeAgo: '4 days ago',
  },
  {
    id: 4,
    title: 'Create bill of Quantity for Project 7',
    time: '2024-03-12 17:00:00',
    isDone: true,
    isPastDue: false,
    isRead: false,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Bryan James' },
    boardLane: { name: 'Backlog' },
    timeAgo: '2 days ago',
  },
  {
    id: 5,
    title: 'Create bill of Quantity for Project 8',
    time: '2024-03-12 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Dirk Williams' },
    boardLane: { name: 'Backlog' },
    timeAgo: '2 days ago',
  },
  {
    id: 6,
    title: 'Create bill of Quantity for Project 9',
    time: '2024-03-16 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Derron Cain' },
    boardLane: { name: 'Backlog' },
    timeAgo: '12 days ago',
  },
  {
    id: 7,
    title: 'Create bill of Quantity for Project 11',
    time: '2024-02-28 17:00:00',
    isDone: false,
    isPastDue: true,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Larry Legend' },
    boardLane: { name: 'Done' },
    timeAgo: '8 days ago',
  },
  {
    id: 8,
    title: 'Create bill of Quantity for Project 12',
    time: '2024-01-18 17:00:00',
    isDone: true,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Marian Sharpe' },
    boardLane: { name: 'Backlog' },
    timeAgo: '20 days ago',
  },
  {
    id: 9,
    title: 'Create bill of Quantity for Project 13',
    time: '2024-03-31 17:00:00',
    isDone: false,
    isPastDue: false,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Allen Miranda' },
    boardLane: { name: 'In Progress' },
    timeAgo: '10 days ago',
  },
  {
    id: 10,
    title: 'Create bill of Quantity for Project 14',
    time: '2024-01-02 17:00:00',
    isDone: false,
    isPastDue: true,
    isRead: true,
    description: 'Lorem ipsum dpsum dolor sit amet, consectetur adipiscing.',
    createdBy: { name: 'Pau Pascual' },
    boardLane: { name: 'Backlog' },
    timeAgo: '10 days ago',
  },
];
